/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b5deb6dcfb86c807d17da94d9cdaa2cf)
interface __BaseEnv_Env {
	ENQUIRIES_DB: D1Database;
	EMAIL: SendEmail;
	FROM_EMAIL: "hello@safouanaouezghar.com";
	NOTIFICATION_EMAIL: "aouezgharsafouan@gmail.com";
	TURNSTILE_SITE_KEY: "0x4AAAAAAEPJzadzcHSZRlOX";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FROM_EMAIL" | "NOTIFICATION_EMAIL" | "TURNSTILE_SITE_KEY">> {}
}
